CREATE TABLE IF NOT EXISTS EMPLOYEE
(
   EMP_ID int PRIMARY KEY,
   EMP_NAME varchar (20) DEFAULT 'SYSTEM'.
   AGE int,
   ADDRESS varchar(4000) ,
   COUNTRY VARCHAR(30)
   EMAIL VARCHAR(50)
);
CREATE TABLE IF NOT EXISTS MY_SEQUENCES
(
   SEQ_NAME varchar (60) PRIMARY KEY,
   NEXT_VAL int not null
);